#!/bin/bash
set -a
shopt -s extglob
RSS='http://develop.twiki.org/~twiki4/cgi-bin/view/Bugs/WebRss'
tdir=../Tasks
tweb=Tasks
if test "x$1" = x; then debug=false; else debug=true;fi

main () {
  init
  get_rss | while read line rest; do
    case "$line" in '<item') read_item "$rest" ;; esac
  done
}

get_rss () {
  if ! $debug; then wget -q -O - "$RSS"
  else if test ! -e /tmp/ifftb; then wget -q -O - "$RSS" >/tmp/ifftb; fi
  fi
  cat /tmp/ifftb
}

read_item () {
  url="${1#*\"}"; url="${url%\"*}"
  while read line; do
    case "$line" in
      '</item>'*) create_item "$title" "$url" "$link" "$desc"; return;;
      '<title>'*) title="${line#*CDATA[[]}"; title="${title%[]][]]*}";;
      '<link>'*)  link="${line#*<link>}"; link="${link%</link>*}";;
      '<description>'*) desc="${line#*CDATA[[]}"; desc="${desc%[]][]]*}";;
    esac
  done
}

create_item () {
  title="$1"; url="$2"; link="$3"; desc="$4"
  name="${url##*/}"; 
  id="${link##*=}"; id="${id//[^a-zA-Z0-9_]/_}"
  file="${name}_$id"; diff="${url/bin\view/bin\/rdiff}?type=history"
  tt=

  case "$name" in Item[0-9]*) : ;; *) return;; esac
  if test -e $file.txt -a ! $debug; then return; fi

  if test -e $tdir/$name.txt; then
    if ! grep -qs UNRELATED_TO_TWIKIBUG_ITEM${name#Item} $tdir/$name.txt; then
      tt="      1. [[$tweb.$name]] (if unrelated, please put the string =UNRELATED_TO_TWIKIBUG_ITEM${name#Item}= in it to avoid further listing)
"
    fi
  fi
  for topic in `grep -lr --include='Item*.txt' $name $tdir`; do
    tname=${topic##*/}
    tt="$tt      1. [[$tweb.${tname%.txt}]]
"
  done
  D file
  cat >$file.txt <<EOF
---+ $title
$desc

   * TWiki bug topic:  [[$url][$name]] (
     [[$url?raw=debug][src]] -
     [[$diff][history]] )
   * Foswiki task topics that seem related:
$tt

%META:FORM{name="InputItemForm"}%
%META:FIELD{name="Status" attributes="" title="Status" value="TODO"}%
%META:FIELD{name="WaitingFor" attributes="" title="Waiting For" value=""}%
%META:FIELD{name="Name" attributes="" title="Name" value="$name"}%
%META:FIELD{name="Desc" attributes="" title="Desc" value="$desc"}%
%META:FIELD{name="Url" attributes="" title="Url" value="$url"}%
EOF
  chmod a+rw $file.txt
}

init () {
  :
}

D () { 
  if $debug; then 
    for v in "$@" ;do eval echo -n '$v=$'"$v "; echo -n ' '; done; echo
  fi
}
DD () { 
  if $debug; then
    for v in "$@" ;do eval echo ':: $v=$'"$v "; done
  fi
}
main
